### ISSUE TITLE
Adding CSS

### ISSUE THREAD

**Issue by celicoo** [toranb/ember-cli-simple-validation#13]
~ DELETED ~

**Comment by toranb** [comment]
I appreciate the PR but I think most addons now avoid shipping css. In the README I mention that you need to add a simple .hidden class.

Sorry this wasn't more clear /etc

**Comment by celicoo** [comment]
Hei @toranb! I'm sorry, but i'm still confuse here.

When someones hits the login new page, the default behavior is to show all the error messages, and when the user types something, the error message fades away?

Thanks.

**Comment by toranb** [comment]
the default behavior (w/out a delay set) looks like this

1) view the user page (all messages are hidden because you've added a css class "hidden" w/ display: none to your stylesheet)
2) the user types something - nothing shows up as the input is valid
3) if the user backspaces all the characters away, the validation shows up (the hidden class is removed)
