### ISSUE TITLE
Validation based on multiple model properties

### ISSUE THREAD

**Issue by caseklim** [toranb/ember-cli-simple-validation#18]
Let's say I have a radio input with two values. If the first value is selected, then another value must be selected in order for my model to be "valid". If the second value is selected, then the model is valid without any additional conditions.

I currently have two validation properties set up, one for the radio input and another for the value dependent on the radio input selection. However, because these are two separate properties, the validation is not being updated properly. I am trying to validate the dependent property using a function passed into `validate`.

Is there a way I can make this more complicated validation update appropriately? If not, I would propose validation based on multiple properties.

It seems what could be contributing to this issue is that `validate` is only called when a property updates, rather than when checking if `this.get('valid')`.

**Comment by toranb** [comment]
@cklimkowsky thanks for writing! I assumed most people just passed on by because I haven't updated this addon in some time :)

Your validation use case is solid and I absolutely agree that we should attempt to add this for people with more complex user interfaces like you suggest. I'll setup a test to describe this and pull you into for feedback.

I'll take a first stab at this tonight/tomorrow night and when I throw up the pull-request I'll close out this issue so we can move ahead/merge something that works for you.

**Comment by caseklim** [comment]
@toranb I have to admit I wasn't sure if I would get a response but I figured you never know until you try :) thank you for replying so quickly!

That would be great, I'm happy to give feedback. Like I mentioned, I think the root of my problem here is that validation fields are only updated when the respective property value updates, rather than when `this.get('valid')` is checked or some dependent property is updated.
